defaults:
  - config_teleop
  - override motion: motion_full
  - override rewards: rewards_teleop_omnih2o_teacher

task: 'robot:teleop'
run_name: "OmniH2O_TEACHER"
notes: ""
num_envs: 1
sim_device: 'cuda:0'
headless: False
stand_on_ground: False

env:
  num_observations: 1665
  num_privileged_obs: 1742
  add_short_history: True 
  short_history_length: 25

motion:
  teleop_obs_version: 'v-teleop-extend-vr-max-nolinvel'
  teleop_selected_keypoints_names: [] 
  extend_head: False 
  motion_file: 'resources/motions/h1/motion_data.pkl'

asset:
  zero_out_far: False 
  termination_scales:
    max_ref_motion_distance: 10.

resume : True
load_run : 25_11_20_21-39-20_OmniH2O_STUDENT # -1 : last run
checkpoint : -1 # -1 : last saved model +


 
     