target: hGPT.models.archs.hgpt_vq.VQVae
params:
  quantizer: 'ema_reset'
  code_num: 512
  code_dim: 512
  output_emb_width: 512
  width: 512
  down_t: 2
  stride_t: 2
  depth: 3
  dilation_growth_rate: 3
  norm: None
  activation: 'relu'
  nfeats: ${DATASET.NFEATS}
