target: hGPT.models.archs.hgpt_vq.VQVae
params:
  quantizer: 'ema_reset'
  code_num: 2048
  code_dim: 2048
  output_emb_width: 2048
  width: 2048
  down_t: 2
  stride_t: 2
  depth: 3
  dilation_growth_rate: 3
  norm: None
  activation: 'relu'
  nfeats: ${DATASET.NFEATS}